### ISSUE TITLE
env.set_task for Navigation2DEnv

### ISSUE THREAD

**Issue by ihzainsangju** [TroddenSpade/Meta-Reinforcement-Learning#1]
Hello! First and foremost, I want to express my appreciation for your great work. I've come across an issue with the ANIL, especially when I want to use `Navigation2DEnv`.

`env.set_task(env.sample_tasks(1)[0])`
`env.set_task(task_config)`

In the `Navigation2DEnv`, there is no `env.set_task` attribute. If I want to use `Navigation2DEnv`, what should I write to replace `set_task`? 
Thank you

**Comment by TroddenSpade** [comment]
Hi @ihzainsangju, I am glad that you found the repo valuable. 
Regarding your issue, although the Navigation2DEnv was defined, the main code in [ANIL.ipynb](https://github.com/TroddenSpade/Meta-Reinforcement-Learning/blob/main/ANIL.ipynb) utilizes the "HalfCheetahForwardBackward-v1" environment. 
Yet, if you would like to try it with the "Navigation2DEnv", the "set_task" method should be defined just in the way we assign tasks within the "reset_task".

```
def reset_task(self, task):
        self._task = task
        self._goal = task['goal']
```
Here, the reset_task takes a task that is a dictionary containing a key, "goal," and a value describing the coordinates of the goal. Instead of writing a new "set_task" method, if you change the name "reset_task" to "set_task," you will also be able to run it with the "Navigation2DEnv".
